### ISSUE TITLE
Compute listings stats

### ISSUE THREAD

**Issue by AlexMerritt** [codeforboston/legalhousing#87]
Compute stats over a time value that is passed in, for example 1 month or 1 year.
Stats format {
NumPosts: "",
NumDiscriminatory : "",
ByPhrase : { "Phrase1" : "", ..., "PhraseN" :""
}

**Comment by Joshhw** [comment]
Hey @smithWEBtek, I was wondering if I could help with this? I had initially joined trying to build out the phrases regex list and analyze for NLP stuff. I missed last two weeks due to comp issues. What exactly does this entail?

**Comment by smithWEBtek** [comment]
Hey Josh great glad to have you work with me on this. I have Ruby methods which parse the phrases according to  Alex's desired data structure {hash example } which he laid out in the issue details. Let's combine with your regex stuff and work together. I'm rehearsing  most of today with musicians so I will be back computer to late tonight. I will send you what I have on my branch in a minute.

**Comment by Joshhw** [comment]
I mightve done something like that as well. I have been waiting on my pull request to be merged. I had initially made a list of regex phrases and put them into the phrases db (if you check open pulls mine is "a few key fixes") I make a few rake commands that check the db and mark when found against the regex phrases I had pushed into my local db. Maybe you're doing something different and would be better then this initial setup. I look forward to seeing it. I won't be around much today either but will periodically check it.

**Comment by smithWEBtek** [comment]
HI Josh,
All good, I took the approach of using Rails and ActiveRecord to create the
DB relationships so that the logic can be accessed and reused in a variety
of ways and a custom route in config/routes.rb.

Essentially it parses each phrase (using the 'check_phrase(phrase)' method
in the Listing.rb model.), against the ad description.  If the ad
description contains the passed in 'phrase', it gets flagged by setting the
ad.discriminatory value to 'true'.
Then it also creates a new record in the PhraseListing (join table), which
then allows easy retrieval of any phrases related to the ad, by calling
'listing.phrases'.

Ultimately we want to render JSON data according to Alex's format, like
this:

      Stats format {
      NumPosts: "",
      NumDiscriminatory : "",
      ByPhrase : { "Phrase1" : "", ..., "PhraseN" :""
      }

One piece of it will be calling 'listing.phrases'..
Another piece will be counting the number of offending phrases discovered.
Finally, we will have a method that takes in a StartDate and EndDate, and
tallies up the phrase counts for that time period.

Rake tasks is find too, but this functionality will need to be accessed
more frequently, so having ActiveRecord relationships where a 'listing
has_many phrases' and a phrase has_many listings', allows this conveniently
with Rails.

This link shows where I'm working, its not ready for pull request, but you
can see the logic emerging:
https://github.com/smithWEBtek/legalhousing/blob/master/app/models/listing.rb

See you Tuesday, glad your machine is back running!


Thank you,

Brad Smith
Web Developer
www.smithWEBtek.com
603-494-4147

**Comment by Joshhw** [comment]
yeah it looks like we did similar things. I didn't think to use check_phrase and instead modded illegal? to do what check all the phrases within the db. you can see my logic here:https://github.com/Joshhw/legalhousing/blob/master/app/models/listing.rb

I did a preload on the phrases to check that are def discriminatory.

EDIT:
my rails experience is limited to this very project so I chose the rake command style just to see results on command. 

I had also started the process of counting up what listings are marked discriminatory:

```
desc 'Check percentage of listings that are discriminatory'
  task check_percent: :environment do
      @count = 0
      @percent_array = Array.new(101, 0)
      Listing.all.each do |listing|
        Phrase.all.each do |phrase|
          if listing.description.match(/#{phrase.content}/i)
              puts "made it to the if statement"
              @count += 1
          end
        end
        puts "out of if statement"
        @percent_array[@count] += 1
        @count = 0
        puts "made it through one listing"
      end
      puts "#{@percent_array}"
  end

```
I haven't pushed this due to the pull request. I figure it would be good to have two arrays to have the percentage count of discrim listings as well as which phrases hit and how many times they were hit.
you can also check my regex list as well. Its called bad_words.csv and its in the slack channel.
